# Generated by Django 4.2.7 on 2024-01-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_attended_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attended_appointment',
            name='prescription',
            field=models.FileField(default='', upload_to='Prescription/'),
        ),
    ]
