# Generated by Django 4.2.7 on 2024-01-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_attended_appointment_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attended_appointment',
            name='prescription',
            field=models.CharField(max_length=100),
        ),
    ]
